=== Softyy/cert-manager-webhook-namecheap/schema/namecheap-config.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "apiUser": {"type": "string", "minLength": 1, "pattern": "\\S"},
    "apiUserSecretRef": {
      "type": "object",
      "properties": {
        "name": {"type": "string", "minLength": 1, "pattern": "\\S"},
        "key": {"type": "string", "minLength": 1, "pattern": "\\S"}
      }
    },
    "apiKeySecretRef": {
      "type": "object",
      "properties": {
        "name": {"type": "string", "minLength": 1, "pattern": "\\S"},
        "key": {"type": "string", "minLength": 1, "pattern": "\\S"}
      },
      "required": ["name", "key"]
    },
    "username": {"type": "string", "minLength": 1, "pattern": "\\S"},
    "usernameSecretRef": {
      "type": "object",
      "properties": {
        "name": {"type": "string", "minLength": 1, "pattern": "\\S"},
        "key": {"type": "string", "minLength": 1, "pattern": "\\S"}
      }
    },
    "clientIP": {"type": "string", "minLength": 1, "pattern": "\\S"},
    "useSandbox": {"type": "boolean"},
    "ttl": {"type": "integer"}
  },
  "required": ["clientIP", "apiKeySecretRef"],
  "allOf": [
    {
      "anyOf": [
        {"required": ["apiUser"]},
        {"required": ["apiUserSecretRef"]}
      ]
    },
    {
      "anyOf": [
        {"required": ["username"]},
        {"required": ["usernameSecretRef"]}
      ]
    },
    {
      "if": {"required": ["apiUserSecretRef"]},
      "then": {"properties": {"apiUserSecretRef": {"required": ["name", "key"]}}}
    },
    {
      "if": {"required": ["usernameSecretRef"]},
      "then": {"properties": {"usernameSecretRef": {"required": ["name", "key"]}}}
    }
  ]
}

=== Softyy/cert-manager-webhook-namecheap/testdata/my-custom-solver/config.json
{
  "apiUserSecretRef": {
    "name": "namecheap-credentials",
    "key": "apiUser"
  },
  "usernameSecretRef": {
    "name": "namecheap-credentials",
    "key": "username"
  },
  "clientIP": "203.0.113.10",
  "apiKeySecretRef": {
    "name": "namecheap-credentials",
    "key": "apiKey"
  },
  "useSandbox": true,
  "ttl": 60
}
